### ISSUE TITLE
无法连接es

### ISSUE THREAD

**Issue by BetterWorld-Liuser** [levonmo/mongo-sync-elasticsearch#1]
es是本地docker启动的，绑定在9200的集群主节点。
使用es-head可以连接。

但是您的程序报错：
ERROR 2020/04/17 14:46:17 connect es  err:no active connection found: no Elasticsearch node available

**Comment by levonmo** [comment]
你看看这个？ https://www.jianshu.com/p/8512c1e8353c
在elasticsearch.yml文件增加这行 network.publish_host: "_local_"，重启试试

**Comment by levonmo** [comment]
> es是本地docker启动的，绑定在9200的集群主节点。
> 使用es-head可以连接。
> 
> 但是您的程序报错：
> ERROR 2020/04/17 14:46:17 connect es err:no active connection found: no Elasticsearch node available

用http能插入和查找数据吗

**Comment by BetterWorld-Liuser** [comment]
成了成了，问题出在我publish甚至成真实ip了，然后阿里云安全组设置是远程机器可访问，把本机的请求阻止了。
谢谢您。

**Comment by levonmo** [comment]
> 成了成了，问题出在我publish甚至成真实ip了，然后阿里云安全组设置是远程机器可访问，把本机的请求阻止了。
> 谢谢您。

那就好，能帮到你很开心，可以要个star吗，谢谢。
