### ISSUE TITLE
无法同步NumberDecimal类型到ES

### ISSUE THREAD

**Issue by hehedalalal** [levonmo/mongo-sync-elasticsearch#11]
想在代码里加一个适配器，能方便介绍下工程结构么。 我想改改代码。

**Comment by hehedalalal** [comment]
已经看了一遍，逻辑都在main函数里

**Comment by levonmo** [comment]
是的是的不好意思，刚刚工作在忙，你能改吗？

**Comment by hehedalalal** [comment]
请问，你用的是什么版本的go？ 我装了1.15.3，但是不支持vendor。

**Comment by levonmo** [comment]
我用的是1.13.8

**Comment by aa476822485** [comment]
![image](https://user-images.githubusercontent.com/9399639/97435435-5e50bd00-195b-11eb-84d7-23e8a5d27695.png)
汗，好些包找不到。

**Comment by mmwl** [comment]
你要那些包，没有的话，我用邮件发给你？我这里可以上外网，啥包都下载
