### ISSUE TITLE
你这个工具为啥同步很慢呢？

### ISSUE THREAD

**Issue by xxdqr** [levonmo/mongo-sync-elasticsearch#12]
我在本地测试了下，win下面，我新增一条记录到MongoDB，要很久才能出现到es中，有没有快速一点的办法，实时同步，还有，有没有办法自定义创建的索引名称，目前是你默认的名称

**Comment by levonmo** [comment]
会有一两秒的延迟，你的延迟有多久

**Comment by levonmo** [comment]
自定义索引暂时还不支持

**Comment by xxdqr** [comment]
10来分钟才会出现


 

-------- 原始邮件 --------
发件人：mmwl <notifications@github.com>
时间：2020年11月9日 14:59
收件人：mmwl/mongo-sync-elasticsearch <mongo-sync-elasticsearch@noreply.github.com>
抄送：xxdqr <xxdqr@163.com>,Author <author@noreply.github.com>
主题：Re: [mmwl/mongo-sync-elasticsearch] 你这个工具为啥同步很慢呢？ (#12)

**Comment by levonmo** [comment]
这个有问题的，你已经完成全量同步的了吗
