### ISSUE TITLE
这个工具是不是不支持mongodb修改的同步

### ISSUE THREAD

**Issue by yusenyi123** [levonmo/mongo-sync-elasticsearch#14]
mongodb中执行下列语句
db.tb3.update({age:1},{$set:{age:11111}},{multi:true})
出现下列错误

INFO 2021/08/05 10:43:23 init config success: [{MongoDB:testdb MongoColl:tb3 MongodbUrl:mongodb://192.168.109.113:27017 EsUrl:http://127.0.0.1:9001 Tspath:./ SyncType:0 ElasticIndex:testdb__tb3}]
INFO 2021/08/05 10:43:23 elastic index is : [testdb__tb3]
INFO 2021/08/05 10:43:23 connect es success
INFO 2021/08/05 10:43:23 connect mongodb success
INFO 2021/08/05 10:43:23 get oplog ts success from file,ts:[{1628130987 6}]
INFO 2021/08/05 10:43:23 start sync increment data...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xf8 pc=0xa18728]

goroutine 1 [running]:
main.main()
        C:/GoWork/src/mongo-sync-elasticsearch/main.go:361 +0x1fc8

**Comment by levonmo** [comment]
支持的，之前有点bug，现在有点bug，现在解决好了，你重新试试
