### ISSUE TITLE
单实例开启oplog 运行错误

### ISSUE THREAD

**Issue by cleverdb** [levonmo/mongo-sync-elasticsearch#3]
您好 ，我单实例开启了oplog 运行信息如下，还有我mongo配置的是远程地址，但是错误里提示成了127.0.0.1地址了
INFO 2020/05/07 13:54:31 connect es success
INFO 2020/05/07 13:54:31 connect mongodb success
ERROR 2020/05/07 13:55:01 find latest oplog.rs err:server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
Addr: 127.0.0.1:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(127.0.0.1:27017[-30]) connection is closed

**Comment by cleverdb** [comment]
在mongdb服务器运行正常了 ，es版本5.1.1，但是同步数据提示
type: _doc, _id: 5eb3bb62c3048a5140fbb4b8, error: {Type:invalid_type_name_exception Reason:Document mapping type name can't start with '_', found: [_doc] ResourceType: ResourceId: Index: Phase: Grouped:false CausedBy:map[] RootCause:[] FailedShards:[]}

**Comment by levonmo** [comment]
现在可以了吗

**Comment by levonmo** [comment]
> 在mongdb服务器运行正常了 ，es版本5.1.1，但是同步数据提示
> type: _doc, _id: 5eb3bb62c3048a5140fbb4b8, error: {Type:invalid_type_name_exception Reason:Document mapping type name can't start with '_', found: [_doc] ResourceType: ResourceId: Index: Phase: Grouped:false CausedBy:map[] RootCause:[] FailedShards:[]}

不知道是不是版本的问题，你试下手动创建es索引？索引名字像这样：mycol.mydb

**Comment by cleverdb** [comment]
应该是es版本问题，index已经创建了，只是没有同步数据，您是基于es那个版本使用？

**Comment by levonmo** [comment]
> 应该是es版本问题，index已经创建了，只是没有同步数据，您是基于es那个版本使用？

es 6的，要不你试试es6？

**Comment by cleverdb** [comment]
哈哈 我在下载最新的7.6.2版本 3q

**Comment by levonmo** [comment]
好的，可以了说下哈

**Comment by cleverdb** [comment]
换了v6.8.8，正常了 ，3q ，star，但是历史数据没有开启oplog，是不是就没有办法同步呢？想了解下您的这个全量同步机制，

**Comment by levonmo** [comment]
其实全量同步没有开启oplog也是可以的，不过现在还不支持，现在只支持全量+增量 。后面可以加一个参数，只进行全量同步

**Comment by cleverdb** [comment]
thanks ，后期优化可以加上index和type配置，然后默认为的db name+col name ，可能还需要优化下 服务和数据库不在同一服务器问题，Servers:
Addr: 127.0.0.1:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(127.0.0.1:27017[-30]) connection is closed 
good luck

**Comment by levonmo** [comment]
好的，谢谢你的建议

**Comment by levonmo** [comment]
新的版本v0.2.0已经支持只增量同步了
