### ISSUE TITLE
mongodb用的SCRAM-SHA-1，报错了报错信息如下

### ISSUE THREAD

**Issue by lei375809291** [levonmo/mongo-sync-elasticsearch#7]
ERROR 2020/07/27 10:25:45 find latest oplog.rs err:connection() : auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-S
HA-1": (AuthenticationFailed) Authentication failed.

**Comment by levonmo** [comment]
可以把你配置文件给我看看吗

**Comment by burakkazoglu** [comment]
if you add this parameter the problem can be solved; `"--authenticationDatabase admin"`
